#include "nsISupports.idl"
#include "nsIDOMWindow.idl"
#include "nsIDOMNode.idl"
#include "CustomButtonParameters.idl"

[scriptable, uuid (64d03940-83bc-4ac6-afc5-3cbf6a7147c5)]
interface cbICustomButtonsService: nsISupports
{
	void editButton (in nsIDOMWindow opener, in string buttonLink, in cbICustomButtonParameters param);
	string cloneButton (in nsIDOMNode clonedButton);
	void removeButton (in nsIDOMNode removedButton, in boolean removeFromOverlay);
	boolean updateButton (in string buttonLink, in string buttonId);
	cbICustomButtonParameters getButtonParameters (in string buttonLink);
	cbICustomButtonParameters parseButtonURI (in AUTF8String uri);
	boolean installWebButton (in cbICustomButtonParameters parameters, in AUTF8String buttonURI, in boolean showConfirmDialog);
	AUTF8String convertImageToRawData (in AUTF8String windowId, in string buttonId, in AUTF8String imageURL);
	AUTF8String getLocaleString (in string stringId);
	string getWindowId (in AUTF8String documentURI);
	AUTF8String getNotificationPrefix (in AUTF8String windowId);
	void register (in nsIDOMWindow window);
	void unregister ();
	void installButton (in cbICustomButtonParameters param);
	void makeOverlay ();
	boolean canUpdate ();
	AUTF8String readFromClipboard ();
	void writeToClipboard (in AUTF8String str);
	string makeButtonLink (in AUTF8String documentURI, in string action, in string buttonId);
	void alert (in string msgId);
};
