#define FIREFOXAPP		application={ec8030f7-c20a-464f-9b0e-13a3a9e97384}
#define FLOCKAPP		application={a463f10c-3994-11da-9945-000d60ca027b}
#define THUNDERBIRDAPP	application={3550f703-e582-4d05-9a08-453d09bdfdc6}
#define SUNBIRDAPP		application={718e30fb-e89b-41dd-9da7-e25a45638b28}

#define BROWSER				chrome://browser/content
#define GLOBAL				chrome://global/content
#define MESSENGER			chrome://messenger/content
#define MESSENGERCOMPOSE	MESSENGER/messengercompose 		
#define CALENDAR			chrome://sunbird/content
#define SUNBIRD				chrome://calendar/content
#define	MOZAPPS				chrome://mozapps/content
#define EXTENSIONS			MOZAPPS/extensions
#define EDITOR				chrome://editor/content
